# Generated by Django 2.0 on 2018-10-01 20:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.IntegerField(max_length=18)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('academy', models.CharField(max_length=512, verbose_name='If valid')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('social_profile', models.CharField(max_length=256)),
                ('website', models.URLField()),
            ],
        ),
    ]
